version: "3.9"

services:
  db:
    container_name: app-db-dv
    image: postgres:latest
    volumes:
      - ./postgre-data:/var/lib/postgresql/data
    env_file:
      - .env.desarrollo
    ports:
      - 5432:5432
    command: ["postgres", "-c", "password_encryption=scram-sha-256"]
  app:
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "sleep 5 && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py shell < load_database.py && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.desarrollo
    volumes:
      - .:/django
    ports:
      - "80:8000"
      - "8081:8081"
    depends_on:
      - db